---
title: "DataComp"
author: "Sophia Freuden"
date: "1/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# The purpose of this rmd is to determine how many unique RT English stories I scraped.
```

```{r}
library(lubridate)
library(tidyverse)
```

```{r}
col_types = cols(
  date = col_character(),
  title = col_character(),
  content = col_character(),
  URL = col_character()
)
```

```{r}
data1 <- read_csv("clinton-civil-society/clinton-civil-society.csv", col_types = col_types)

data1 <- data1 %>%
  mutate(date = dmy(date))
```

```{r}
data2 <- read_csv("mcfaul/mcfaul.csv", col_types = col_types)

data2 <- data2 %>%
  mutate(date = dmy(date))
```

```{r}
data3 <- read_csv("orange-revolution/orange-revolution.csv", col_types = col_types)

data3 <- data3 %>%
  mutate(date = dmy(date))
```

```{r}
data4 <- read_csv("soros-civil-society/soros-civil-society.csv", col_types = col_types)

data4 <- data4 %>%
  mutate(date = dmy(date))
```

```{r}
data5 <- read_csv("soros-democratic-party/soros-democratic-party.csv", col_types = col_types)

data5 <- data5 %>%
  mutate(date = dmy(date))
```

```{r}
data6 <- read_csv("soros-elections/soros-elections.csv", col_types = col_types)

data6 <- data6 %>%
  mutate(date = dmy(date))
```

```{r}
data7 <- read_csv("soros-open-society/soros-open-society.csv", col_types = col_types)

data7 <- data7 %>%
  mutate(date = dmy(date))
```

```{r}
data8 <- read_csv("soros-russia/soros-russia.csv", col_types = col_types)

data8 <- data8 %>%
  mutate(date = dmy(date))
```

```{r}
data9 <- read_csv("stop-soros/stop-soros.csv", col_types = col_types)

data9 <- data9 %>%
  mutate(date = dmy(date))
```

```{r}
data10 <- read_csv("clinton-maidan/clinton-maidan.csv", col_types = col_types)

data10 <- data10 %>%
  mutate(date = dmy(date))
```
 
```{r}
data11 <- read_csv("clinton-orange-revolution/clinton-orange-revolution.csv", col_types = col_types)

data11 <- data11 %>%
  mutate(date = dmy(date))

## NOTE IF YOU MAKE MORE PAST THIS: THERE IS ALREADY A data12
```

```{r}
data12 <- bind_rows(data1, data2)
```

```{r}
data123 <- bind_rows(data12, data3)
```

```{r}
data1234 <- bind_rows(data123, data4)
```

```{r}
data12345 <- bind_rows(data1234, data5)
```

```{r}
data123456 <- bind_rows(data12345, data6)
```

```{r}
data1234567 <- bind_rows(data123456, data7)
```

```{r}
data12345678 <- bind_rows(data1234567, data8)
```

```{r}
data123456789 <- bind_rows(data12345678, data9)
```

```{r}
data12345678910 <- bind_rows(data123456789, data10)
```

```{r}
all_data <- bind_rows(data12345678910, data11)
```

```{r}
u <- unique(all_data$URL)
# u is a character vector length 912; raw all_data length 1396.
```

```{r}
data45 <- bind_rows(data4, data5)
```

```{r}
data456 <- bind_rows(data45, data6)
```

```{r}
data4567 <- bind_rows(data456, data7)
```

```{r}
data45678 <- bind_rows(data4567, data8)
```

```{r}
all_soros <- bind_rows(data45678, data9)
```

```{r}
u_soros <- unique(all_soros$URL)
# u_soros is a character vector length 429; raw all_soros length 866.
```

```{r}
clinton110 <- bind_rows(data1, data10)
```

```{r}
all_clinton <- bind_rows(clinton110, data11)
```

```{r}
u_clinton <- unique(all_clinton$URL)
# u_clinton is a character vector length 163; raw all_clinton length 168.
```

```{r}
# u_soros: 429; u_clinton: 163; mcfaul: 200; orange revolution: 162. The sums of these != u as there is some overlap between them (but not within them).
```

```{r}
# Search terms that are too big to have found results for:
# clinton protests: 300+
# clinton elections: 300+
# clinton democratic party: 300+
# clinton russia: 300+
# clinton putin: 300+
# clinton ukraine: 300+

# Could do:
# clinton soros: 119 (Won't do because of issues with bias and redundancy.)
# clinton duma: 90

# Too small:
# clinton soros mcfaul: 0

# Order of search terms doesn't matter.
```









