---
title: "StoryExtractor"
author: "Sophia Freuden"
date: "1/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tm)
library(SnowballC)
library(textclean)
library(lubridate)
library(tidyverse)

# See code chunk titled "extractor" on how to pull a specific story from an RT search term by internal term (i.e. look for story with most hits for "russia" within search term "stop soros").
```

```{r}
col_types = cols(
  date = col_character(),
  title = col_character(),
  content = col_character(),
  URL = col_character()
)
```

```{r}
# Be sure to use correct data files for your chosen individual. Leave others commented out.

# clinton:
data1 <- read_csv("clinton-civil-society/clinton-civil-society.csv", col_types = col_types)
data2 <- read_csv("clinton-maidan/clinton-maidan.csv", col_types = col_types)
data3 <- read_csv("clinton-orange-revolution/clinton-orange-revolution.csv",
                 col_types = col_types)
data4 <- read_csv("clinton-duma/clinton-duma.csv",
                 col_types = col_types)

# mcfaul:
# data4 <- read_csv("mcfaul/mcfaul.csv", col_types = col_types)

# Skipping over Orange Revolution in Final Version
# dataX <- read_csv("orange-revolution/orange-revolution.csv", col_types = col_types)

# soros:
# data5 <- read_csv("soros-civil-society/soros-civil-society.csv", col_types = col_types)
# data6 <- read_csv("soros-democratic-party/soros-democratic-party.csv", col_types = col_types)
# data7 <- read_csv("soros-elections/soros-elections.csv", col_types = col_types)
# data8 <- read_csv("soros-eu/soros-eu.csv", col_types = col_types)
# data9 <- read_csv("soros-globalism/soros-globalism.csv", col_types = col_types)
# data10 <- read_csv("soros-nato/soros-nato.csv", col_types = col_types)
# data11<- read_csv("soros-open-society/soros-open-society.csv", col_types = col_types)
# data12 <- read_csv("soros-russia/soros-russia.csv", col_types = col_types)
# data13 <- read_csv("stop-soros/stop-soros.csv", col_types = col_types)
```

```{r}
# clinton

data12 <- bind_rows(data1, data2)

data123 <- bind_rows(data12, data3)

all_clinton <- bind_rows(data123, data4)

data <- unique(all_clinton)
```

```{r}
# soros

# data56 <- bind_rows(data5, data6)
# data567 <- bind_rows(data56, data7)
# data5678 <- bind_rows(data567, data8)
# data56789 <- bind_rows(data5678, data9)
# data5678910 <- bind_rows(data56789, data10)
# data567891011 <- bind_rows(data5678910, data11)
# data56789101112 <- bind_rows(data567891011, data12)
# all_soros <- bind_rows(data56789101112, data13)
# 
# data <- unique(all_soros)
```

```{r}
# mcfaul

# data <- data4
```

```{r}
data <- data %>%
  mutate(date = dmy(date))
```

```{r}
Encoding(data$content) <- "latin1"
data$content <- replace_non_ascii(data$content)

corpus <- SimpleCorpus(VectorSource(data$content))
corpus <- tm_map(corpus, stripWhitespace)
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeWords, stopwords("english"))

nonstem.corpus <- corpus
corpus <- tm_map(corpus, stemDocument)

nDTM <- DocumentTermMatrix(nonstem.corpus)
DTM <- DocumentTermMatrix(corpus)

sums2 <- as.data.frame(as.matrix(nDTM))
sums2d <- as.data.frame(as.matrix(DTM))

sums2$ArtDate <- data$date
sums2d$ArtDate <- data$date

sums2$URL <- data$URL
sums2d$URL <- data$URL
```

```{r extractor}
# This code chunk will select a date and term from the non-stemmed DTM that you can view and find the URL for.
temp <- sums2 %>% select(c(ArtDate, clinton, URL))
temp <- unique(temp)
temp <- temp %>% mutate(year = year(ArtDate))
temp <- temp %>% filter(year >= 2015)
# temp2 <- sums2d %>% select(c(ArtDate, ukrain, URL))
# temp2 <- unique(temp2)
view(temp)

head1 <- temp  %>% arrange(desc(clinton))
head1 <- head(head1, 10)
view(head1)

print(head1$URL[1])
print(head1$URL[2])
print(head1$URL[3])
print(head1$URL[4])
print(head1$URL[5])
print(head1$URL[6])
print(head1$URL[7])
print(head1$URL[8])
print(head1$URL[9])
print(head1$URL[10])

# sample: 89 sum: 494, 0.1802 > .10
```

```{r}
sums2 %>%
  group_by(ArtDate) %>% 
  summarise(Frequency = sum(brexit)) %>%
  ggplot(aes(x = ArtDate, y = Frequency)) +
  geom_point() +
  geom_smooth(method = 'loess') +
  labs(
    title = "Term Frequency Per Article Over Time",
    subtitle = "Term: 'brexit,' RT Search Term: 'stop soros'",
    x = "Date",
    y = "Frequency"
    # Comment/uncomment caption below as needed. Add/delete comma in line above, too.
    # caption = "Stemmed."
  ) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```





